version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
      - PORT=3000
      - HOST=0.0.0.0
      - SESSION_SECRET=${SESSION_SECRET}
      - API_KEY=${API_KEY}
      - DEFAULT_MODEL_ID=${DEFAULT_MODEL_ID}
      - DEFAULT_BASE_URL=${DEFAULT_BASE_URL}
      - DEFAULT_API_KEY=${DEFAULT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: >
      sh -c "npx prisma migrate deploy && 
             node src/setup.js && 
             npm start"